//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Team35Entities : DbContext
    {
        public Team35Entities()
            : base("name=Team35Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DISTRICT> DISTRICTs { get; set; }
        public DbSet<FEATURE> FEATUREs { get; set; }
        public DbSet<PROJECT_STATUS> PROJECT_STATUS { get; set; }
        public DbSet<PROPERTY> PROPERTies { get; set; }
        public DbSet<PROPERTY_FEATURE> PROPERTY_FEATURE { get; set; }
        public DbSet<PROPERTY_TYPE> PROPERTY_TYPE { get; set; }
        public DbSet<STREET> STREETs { get; set; }
        public DbSet<USER> USERs { get; set; }
        public DbSet<WARD> WARDs { get; set; }
    }
}
